=== engalar/MendixModelSDKDemo/src/lib/page/page.schema.json
{
    "$schema": "http://json-schema.org/draft-07/schema#",
    "type": "object",
    "properties": {
        "type": { "type": "string", "enum": ["Page"] },
        "description": { "type": "string" },
        "name": { "type": "string" },
        "canvasWidth": { "type": "integer" },
        "title": {
            "type": "object",
            "properties": {
                "languageCode": { "type": "string" },
                "text": { "type": "string" }
            },
            "required": ["languageCode", "text"]
        },
        "layout": { "$ref": "#/definitions/layout" },
        "allowedRoles": {
            "type": "array",
            "items": { "type": "string" }
        },
        "include": {
            "type": "array",
            "items": { "type": "string" }
        }
    },
    "required": [
        "type",
        "name",
        "canvasWidth",
        "title",
        "layout",
        "allowedRoles"
    ],
    "definitions": {
        "layout": {
            "type": "object",
            "properties": {
                "type": { "type": "string", "enum": ["Layout"] },
                "description": { "type": "string" },
                "name": { "type": "string" },
                "arguments": {
                    "type": "array",
                    "items": {
                        "type": "object",
                        "properties": {
                            "parameter": { "type": "string" },
                            "widgets": {
                                "type": "array",
                                "items": { "$ref": "#/definitions/widget" }
                            }
                        },
                        "required": ["parameter", "widgets"]
                    }
                }
            },
            "required": ["type", "name", "arguments"]
        },
        "widget": {
            "type": "object",
            "properties": {
                "type": { "type": "string" },
                "description": { "type": "string" },
                "name": { "type": "string" },
                "appearance": {
                    "type": "object",
                    "properties": {
                        "class": { "type": "string" },
                        "designProperties": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "key": { "type": "string" },
                                    "value": { "type": "string" }
                                },
                                "required": ["key", "value"]
                            }
                        }
                    }
                },
                "content": {
                    "type": "object",
                    "properties": {
                        "translations": {
                            "type": "array",
                            "items": {
                                "type": "object",
                                "properties": {
                                    "languageCode": { "type": "string" },
                                    "text": { "type": "string" }
                                },
                                "required": ["languageCode", "text"]
                            }
                        }
                    }
                },
                "renderMode": { "type": "string" },
                "rows": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/row" }
                }
            },
            "required": ["type", "name"]
        },
        "row": {
            "type": "object",
            "properties": {
                "type": { "type": "string", "enum": ["Row"] },
                "description": { "type": "string" },
                "columns": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/column" }
                }
            },
            "required": ["type", "columns"]
        },
        "column": {
            "type": "object",
            "properties": {
                "type": { "type": "string", "enum": ["Column"] },
                "description": { "type": "string" },
                "weight": { "type": "integer" },
                "widgets": {
                    "type": "array",
                    "items": { "$ref": "#/definitions/widget" }
                }
            },
            "required": ["type", "weight", "widgets"]
        }
    }
}

=== engalar/MendixModelSDKDemo/src/lib/page/model/Home_Web.page.json
{
    "$schema": "../schemas/page.schema.json",
    "type": "Page",
    "name": "Home_Web",
    "canvasWidth": 1200,
    "title": {
        "languageCode": "en_US",
        "text": "Homepage"
    },
    "layout": {
        "type": "Layout",
        "name": "Atlas_Core.Atlas_Default",
        "arguments": [
            {
                "parameter": "Atlas_Core.Atlas_Default.Main",
                "widgets": [
                    {
                        "type": "LayoutGrid",
                        "name": "layoutGrid1",
                        "appearance": {},
                        "rows": [
                            {
                                "type": "Row",
                                "columns": [
                                    {
                                        "type": "Column",
                                        "weight": -1,
                                        "widgets": [
                                            {
                                                "type": "DivContainer",
                                                "name": "container1",
                                                "appearance": {
                                                    "class": "pageheader"
                                                },
                                                "widgets": [
                                                    {
                                                        "type": "LayoutGrid",
                                                        "name": "layoutGrid2",
                                                        "appearance": {},
                                                        "rows": [
                                                            {
                                                                "type": "Row",
                                                                "columns": [
                                                                    {
                                                                        "type": "Column",
                                                                        "weight": -1,
                                                                        "widgets": [
                                                                            {
                                                                                "type": "DynamicText",
                                                                                "name": "text1",
                                                                                "appearance": {
                                                                                    "class": "pageheader-title",
                                                                                    "designProperties": [
                                                                                        {
                                                                                            "key": "Spacing bottom",
                                                                                            "value": "Outer small"
                                                                                        }
                                                                                    ]
                                                                                },
                                                                                "content": {
                                                                                    "translations": [
                                                                                        {
                                                                                            "languageCode": "nl_NL",
                                                                                            "text": "Tekst"
                                                                                        },
                                                                                        {
                                                                                            "languageCode": "en_US",
                                                                                            "text": "Home"
                                                                                        }
                                                                                    ]
                                                                                },
                                                                                "renderMode": "H3"
                                                                            }
                                                                        ]
                                                                    }
                                                                ]
                                                            }
                                                        ]
                                                    }
                                                ]
                                            }
                                        ]
                                    }
                                ]
                            }
                        ]
                    }
                ]
            }
        ]
    },
    "allowedRoles": ["MyFirstModule.User"]
}
